spring:
      profiles:
        active: dev

   #   datasource:
    #    url: ${JDBC_CONNECTION_STRING}
    #    username: ${JDBC_USER}
     #   password: ${JDBC_PASSWORD}
     #   driverClassName: com.mysql.cj.jdbc.Driver

      jpa:
        show-sql: true
        generate-ddl: false
        properties:
          hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:

          jdbc.batch_size:  100
          jdbc.time_zone: UTC
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          ddl-auto: update

      datasource:
       url: jdbc:mysql://localhost:3306/hifinitedb?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
       username: root
       password: biddiaSQL
       driverClassName: com.mysql.cj.jdbc.Driver

#carpark.csv.url: csv/HDBCarparkInformation.csv
#onemap.token.url: https://www.onemap.gov.sg/api/auth/post/getToken
#onemap.user: ricksonmenezes@gmail.com
#onemap.password: rIcks@n12345
#onemap.converter.url: https://www.onemap.gov.sg/api/common/convert/3414to4326
#onemap.carpark.availability.url: https://api.data.gov.sg/v1/transport/carpark-availability