version: '3.1'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: testdb
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
          test: ["CMD-SHELL", 'mysqladmin ping']
          interval: 10s
          timeout: 2s
          retries: 10

  web:
      image: assignment
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      depends_on:
        db:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_HIBERNATE_NAMING_IMPLICIT_STRATEGY: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
volumes:
  db_data: {}